In [ ]:
from pathlib import Path

import pandas as pd

In [18]:
TRAIN_FILE = Path("../data/raw/train.csv")
TEST_FILE = Path("../data/raw/test.csv")

In [19]:
df_raw_train = pd.read_csv(TRAIN_FILE)
df_raw_test = pd.read_csv(TEST_FILE)

In [21]:
df_raw_train.describe()

                                  text                  category
count                            10003                     10003
unique                           10003                        77
top     I am still waiting on my card?  card_payment_fee_charged
freq                                 1                       187

In [22]:
df_raw_test.describe()

                            text      category
count                       3080          3080
unique                      3080            77
top     How do I locate my card?  card_arrival
freq                           1            40

In [23]:
df_raw_train.category.value_counts()

category
card_payment_fee_charged                            187
direct_debit_payment_not_recognised                 182
balance_not_updated_after_cheque_or_cash_deposit    181
wrong_amount_of_cash_received                       180
cash_withdrawal_charge                              177
                                                   ...
lost_or_stolen_card                                  82
card_swallowed                                       61
card_acceptance                                      59
virtual_card_not_working                             41
contactless_not_working                              35
Name: count, Length: 77, dtype: int64

In [24]:
df_raw_test.category.value_counts()

category
card_arrival                        40
card_linking                        40
exchange_rate                       40
card_payment_wrong_exchange_rate    40
extra_charge_on_statement           40
                                    ..
cash_withdrawal_charge              40
card_about_to_expire                40
apple_pay_or_google_pay             40
verify_my_identity                  40
country_support                     40
Name: count, Length: 77, dtype: int64